application:
  bindAddress: :8445
  production: false
  debug: false
database:
  address: localhost:3401
  name: portfolio
  username: tradalia
  password: tradalia
authentication:
  authority: https://algotiqa-server:8443/auth/realms/algotiqa
  clientId: algotiqa-backend
  clientSecret: ddKGvsqWMKQT4v4lWS03Jr9i3ZEJHzv1
platform:
  storage: https://algotiqa-server:8452/api/storage
  data   : https://algotiqa-server:8446/api/collector
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
